name: flutter_feed_reaction
description: A Flutter package providing you with highly customizable reactions
  list for posts/comments in a Social Media kind of an app.
version: 0.0.6
homepage: https://github.com/shrijanRegmi/flutter_feed_reaction
repository: https://github.com/shrijanRegmi/flutter_feed_reaction

environment:
   sdk: '>=3.1.1 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  flutter_portal: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

assets:
  - assets/emojies/
  - assets/lottie/
